
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"   # Porta para o seu código Python se conectar
      - "15672:15672" # Porta para o painel visual no navegador
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"   # Porta para o seu código Python se conectar